[project]
name = "veneto_cf_verifica"
version = "0.1.0"
description = "PyTorch CUDA project with RTX 50xx support"
requires-python = "==3.12.*"
dependencies = [
    # PyTorch nightly packages
    "torch",
    "torchvision",
    "torchaudio",

    # Other stable dependencies
    "numpy>=2.3.2",
    "pillow>=11.3.0",
    "tqdm>=4.67.1",
    "cryptography>=45.0.5",
    "accelerate>=1.9.0",
    "optimum[onnxruntime-gpu]>=1.26.1",
    "onnxruntime-gpu>=1.22.0",
    "more-itertools>=10.7.0",
    "opencv-python>=4.11.0.86",
    "matplotlib>=3.10.5",
    "albumentations>=2.0.8",
]

[tool.pdm]
distribution = true
